/* English question bank. Keyed by question id; t = question text, e = expected evidence.
   Regulatory citations in the source column are translated by rule in i18n.js. */

const QUESTIONS_EN = {

/* D1 — Governance and Compliance Programme */
'D1-01': { t: 'Have the compliance officer and deputy been appointed in line with the regulation and notified to the regulator?', e: 'Appointment decision, regulator notification letter' },
'D1-02': { t: 'Does the compliance officer have a direct reporting line to the board?', e: 'Organisation chart, job description' },
'D1-03': { t: 'Does removal of the compliance officer require a board decision and regulator notification?', e: 'Procedure text' },
'D1-04': { t: 'Is the compliance officer free of business-unit duties that could create a conflict of interest?', e: 'Job description, list of secondary duties' },
'D1-05': { t: 'Does the compliance officer have unrestricted access to all customer, transaction and system data?', e: 'Authorisation matrix' },
'D1-06': { t: 'Are the compliance function budget and headcount approved annually by the board?', e: 'Board decision, budget approval' },
'D1-07': { t: 'Is compliance headcount (FTE) based on a capacity analysis driven by customer and alert volumes?', e: 'Capacity analysis document' },
'D1-08': { t: 'Is there a succession and business continuity plan for key compliance roles?', e: 'Continuity plan' },
'D1-09': { t: 'Does the compliance programme cover policy, risk management, monitoring and control, training and internal audit in full?', e: 'Compliance programme document' },
'D1-10': { t: 'Has the AML/CFT policy been approved by the board and reviewed within the last 12 months?', e: 'Approved policy, revision date' },
'D1-11': { t: 'Are procedures subject to version control and documented ownership consistent with the policy?', e: 'Document management record' },
'D1-12': { t: 'Is a consistent AML policy applied at group level (foreign branches and subsidiaries)?', e: 'Group policy, local addenda' },
'D1-13': { t: 'Is there an escalation procedure for cases where local law conflicts with group policy?', e: 'Procedure, conflict log' },
'D1-14': { t: 'Is AML/CFT internal audit included in the annual audit plan and independent of the first and second lines?', e: 'Audit plan, audit report' },
'D1-15': { t: 'Are internal audit findings tracked to closure and independently re-tested?', e: 'Finding tracker, re-test record' },
'D1-16': { t: 'Is AML risk approval (NPA) obtained before new products, services, channels and technologies go live?', e: 'NPA form, approval record' },
'D1-17': { t: 'Are AML responsibilities contractually assigned in outsourcing, agent and representative relationships?', e: 'Sample contracts' },
'D1-18': { t: 'Where customer due diligence is performed by a third party, can the documents be obtained without delay?', e: 'Document request and response log' },
'D1-19': { t: 'Is disciplinary action and consequence management for compliance breaches defined?', e: 'Disciplinary policy, applied cases' },
'D1-20': { t: 'Is there a whistleblowing channel with protection against retaliation?', e: 'Channel definition, usage statistics' },

/* D2 — Customer Profile and Geographic Risk */
'D2-01': { t: 'Is the distribution of the customer base by risk level reported regularly?', e: 'Risk distribution report' },
'D2-02': { t: 'Are changes in the high-risk customer ratio presented periodically to senior management?', e: 'Management report' },
'D2-03': { t: 'For legal entity customers, does the business sector (NACE/MCC) feed into risk scoring?', e: 'Risk model document' },
'D2-04': { t: 'Are cash-intensive sector customers monitored as a separate portfolio?', e: 'Portfolio definition, monitoring scenario' },
'D2-05': { t: 'Is the PEP inventory kept current, distinguishing domestic, foreign and international organisation PEPs?', e: 'PEP list, classification rule' },
'D2-06': { t: 'Are family members and close associates (RCAs) of PEPs identified?', e: 'Identification method, sample file' },
'D2-07': { t: 'Do establishing and continuing a PEP relationship require senior management approval?', e: 'Approval records' },
'D2-08': { t: 'Is the high-risk country list built from FATF black/grey lists, EU high-risk third countries and internal criteria?', e: 'Country risk methodology' },
'D2-09': { t: 'Does the country risk methodology include corruption, terrorist financing, sanctions, tax haven and narcotics indicators?', e: 'Methodology document, indicator sources' },
'D2-10': { t: 'Are country risk scores updated at least annually and on list changes?', e: 'Update log' },
'D2-11': { t: 'Are the customer\'s nationality, residence, transaction geography and source-of-funds country assessed separately?', e: 'Risk model fields' },
'D2-12': { t: 'Is EDD triggered automatically for customers and transactions linked to high-risk countries?', e: 'System rule, sample file' },
'D2-13': { t: 'Is a due diligence questionnaire (e.g. Wolfsberg CBDDQ) obtained for correspondent banking relationships?', e: 'Completed CBDDQ files' },
'D2-14': { t: 'Does establishing a correspondent relationship require senior management approval?', e: 'Approval records' },
'D2-15': { t: 'Are nested correspondent relationships and payable-through accounts detected?', e: 'Detection method, cases identified' },
'D2-16': { t: 'Is the prohibition on relationships with shell banks enforced systemically?', e: 'Control definition' },
'D2-17': { t: 'Are the risk levels of the countries hosting foreign branches and subsidiaries consistent with the institution\'s risk appetite?', e: 'Country–subsidiary risk matrix' },
'D2-18': { t: 'Are customers structured through offshore, free zone or tax haven vehicles separately flagged?', e: 'Flagging rule, customer list' },
'D2-19': { t: 'Is the institution\'s prohibited country/sector list defined and checked at onboarding?', e: 'Prohibited list, system control' },
'D2-20': { t: 'Is the consistency between the customer risk distribution and the alert and STR distribution analysed?', e: 'Comparative analysis report' },

/* D3 — Product and Channel Risk */
'D3-01': { t: 'Is a current inventory maintained for all products and services?', e: 'Product inventory' },
'D3-02': { t: 'Has an inherent ML/TF risk score been assigned to each product?', e: 'Product risk score table' },
'D3-03': { t: 'Does product risk scoring include anonymity, transaction speed, geographic reach, cash intensity and acceptance of third-party funds?', e: 'Scoring methodology' },
'D3-04': { t: 'Is AML and sanctions impact a mandatory assessment item in the new product approval process?', e: 'NPA form' },
'D3-05': { t: 'Are liveness detection and document verification controls applied in non-face-to-face onboarding?', e: 'System configuration, sample record' },
'D3-06': { t: 'Is the detection rate for forged or manipulated documents measured and reported?', e: 'Detection statistics' },
'D3-07': { t: 'For third-party transactions arriving through API or open banking, can the source of funds be traced?', e: 'Data flow diagram' },
'D3-08': { t: 'Are there additional monitoring scenarios for unattended channels such as ATMs and kiosks?', e: 'Scenario list' },
'D3-09': { t: 'Are loading and spending limits on prepaid cards and e-money products set on a risk basis?', e: 'Limit table' },
'D3-10': { t: 'Are product-level thresholds and controls defined for cash transactions?', e: 'Threshold table' },
'D3-11': { t: 'Are virtual asset service provider (VASP) relationships managed as a separate risk category?', e: 'VASP customer list, risk rule' },
'D3-12': { t: 'Is the Travel Rule (originator and beneficiary information) applied to virtual asset transfers?', e: 'System record, sample transfer' },
'D3-13': { t: 'Are there additional controls for transactions involving self-hosted (unhosted) wallets?', e: 'Control definition' },
'D3-14': { t: 'Has a separate AML/sanctions risk assessment been performed for trade finance products?', e: 'Trade finance risk assessment' },
'D3-15': { t: 'Is instrument-level sanctions screening performed for securities and investment products?', e: 'ISIN/instrument screening record' },
'D3-16': { t: 'Is the identification threshold for occasional transactions applied correctly?', e: 'System rule, sample transaction' },
'D3-17': { t: 'Are transactions conducted through the agent and representative channel monitored separately?', e: 'Channel-level monitoring report' },
'D3-18': { t: 'Is there a mechanism to restrict or terminate products whose risk falls outside the institution\'s appetite?', e: 'Decision record' },

/* D4 — Transaction Universe and Data Integrity */
'D4-01': { t: 'Has the full inventory of transaction types subject to monitoring (the transaction universe) been documented?', e: 'Transaction universe document' },
'D4-02': { t: 'Are transaction types excluded from monitoring justified and approved?', e: 'Exclusion list and rationale' },
'D4-03': { t: 'Is the proportion of branch and subsidiary data included in central monitoring known?', e: 'Coverage report' },
'D4-04': { t: 'Is regular reconciliation performed between source systems and the monitoring system?', e: 'Reconciliation reports' },
'D4-05': { t: 'Are thresholds and an escalation procedure defined for reconciliation variances?', e: 'Procedure, escalation records' },
'D4-06': { t: 'Is there an alerting and reprocessing mechanism for data feed failures?', e: 'Error log, reprocessing record' },
'D4-07': { t: 'Is the completeness rate of critical fields (amount, currency, counterparty, country, IBAN, name) measured?', e: 'Data quality report' },
'D4-08': { t: 'Is an acceptable threshold defined for missing or erroneous data rates?', e: 'Threshold definition' },
'D4-09': { t: 'Are data quality indicators included in regular management reporting?', e: 'Management report' },
'D4-10': { t: 'Is reference data used in the monitoring system (country, exchange rate, MCC, sector) kept current?', e: 'Reference data update log' },
'D4-11': { t: 'For multi-currency transactions, is threshold conversion performed from a consistent rate source?', e: 'Rate source definition' },
'D4-12': { t: 'Has the linkage between customer static data and transaction data been verified?', e: 'Matching test report' },
'D4-13': { t: 'Is the completeness of originator and beneficiary information in payment messages checked?', e: 'Control rule, exception report' },
'D4-14': { t: 'Is a suspension, return or information-request procedure applied to transfers with missing information?', e: 'Transaction decision records' },
'D4-15': { t: 'Are transaction and customer records retained and accessible for the minimum period required by law?', e: 'Retention policy, archive test' },
'D4-16': { t: 'Is data integrity testing performed after system changes or data migration?', e: 'Test report' },
'D4-17': { t: 'Can scenarios be validated in a test environment with production-like data?', e: 'Test environment definition' },
'D4-18': { t: 'Are data access rights role-based, restricted and logged?', e: 'Authorisation matrix, access log' },

/* D5 — Customer Lifecycle (CDD/EDD) */
'D5-01': { t: 'Does identification cover all customer types (individuals, legal entities, unincorporated bodies, trust-like structures)?', e: 'Procedure, sample files' },
'D5-02': { t: 'Is identity information verified against reliable and independent sources?', e: 'Verification records (civil registry, trade registry)' },
'D5-03': { t: 'Are the authority and identity of persons acting on the customer\'s behalf separately established?', e: 'Power of attorney, signature circular' },
'D5-04': { t: 'Are transactions systemically blocked until full customer due diligence is complete?', e: 'System control, exception list' },
'D5-05': { t: 'Is the customer acceptance policy written and does it include rejection criteria?', e: 'Acceptance policy' },
'D5-06': { t: 'Does acceptance of a high-risk customer require senior management approval?', e: 'Approval records' },
'D5-07': { t: 'Is beneficial ownership traced through layered structures using both an ownership threshold and control tests?', e: 'Ownership chart, identification file' },
'D5-08': { t: 'Where the beneficial owner cannot be identified, is reliance on the senior managing official justified?', e: 'Rationale records' },
'D5-09': { t: 'Are additional controls applied to trusts, foundations, bearer shares and nominee structures?', e: 'Additional control procedure, sample file' },
'D5-10': { t: 'Is declared beneficial ownership information compared with official registry records and discrepancies reported?', e: 'Comparison record, discrepancy report' },
'D5-11': { t: 'Is the customer risk rating model written, weighted and approved?', e: 'Model document, approval record' },
'D5-12': { t: 'Is the risk rating model subject to independent validation at least annually?', e: 'Validation report' },
'D5-13': { t: 'Are manual overrides of the model output recorded with a rationale and approval?', e: 'Override records' },
'D5-14': { t: 'Is the override rate monitored and are abnormal trends analysed?', e: 'Override statistics' },
'D5-15': { t: 'On trigger events (adverse media, becoming a PEP, transaction anomaly) is the risk score updated without delay?', e: 'Trigger rule, sample case' },
'D5-16': { t: 'Are EDD triggers defined in writing?', e: 'EDD procedure' },
'D5-17': { t: 'Under EDD, is source of funds (SoF) verified against documentary evidence?', e: 'SoF documents' },
'D5-18': { t: 'Is source of wealth (SoW) supported by independent evidence beyond customer declaration?', e: 'SoW file' },
'D5-19': { t: 'Is adverse media screening performed both at onboarding and periodically?', e: 'Screening records' },
'D5-20': { t: 'Are EDD files submitted for senior management approval?', e: 'Approval records' },
'D5-21': { t: 'Is the periodic review frequency differentiated by risk level?', e: 'Frequency table' },
'D5-22': { t: 'Are the number and ageing of overdue KYC files reported?', e: 'Ageing report' },
'D5-23': { t: 'Are transaction restrictions or escalation applied for overdue KYC?', e: 'Restriction records' },
'D5-24': { t: 'Is the customer profile compared against actual transaction behaviour?', e: 'Profile–behaviour analysis report' },
'D5-25': { t: 'Is reactivation of a dormant account defined as a trigger event?', e: 'Scenario definition' },
'D5-26': { t: 'Is the completeness of customer files tested through regular QA sampling?', e: 'QA test report' },

/* D6 — Financial Sanctions and Screening */
'D6-01': { t: 'Is the inventory of applicable sanctions lists (UN, OFAC, EU, UK OFSI, national decisions) defined?', e: 'List inventory' },
'D6-02': { t: 'Is an SLA defined and measured for the time a list update takes to reach production from the source?', e: 'SLA definition, update logs' },
'D6-03': { t: 'Is the entire customer base rescreened after a list update?', e: 'Rescreening logs' },
'D6-04': { t: 'Are national freezing decisions implemented without delay?', e: 'Decision implementation records' },
'D6-05': { t: 'Are national and international list obligations managed separately and in line with their respective scopes?', e: 'Scope matrix' },
'D6-06': { t: 'Is indirect ownership (the 50 percent rule) screened for?', e: 'Screening method, cases identified' },
'D6-07': { t: 'Is the data source used for indirect ownership identification defined and current?', e: 'Data source contract/coverage' },
'D6-08': { t: 'Is sanctions exposure arising from control other than ownership (management, power of attorney, de facto control) assessed?', e: 'Assessment record' },
'D6-09': { t: 'Are sectoral restrictions and dual-use goods controls included in scope?', e: 'Control definition' },
'D6-10': { t: 'Has the fuzzy matching threshold been calibrated and the rationale documented?', e: 'Calibration report' },
'D6-11': { t: 'Has threshold calibration been repeated within the last 12 months?', e: 'Date of last calibration' },
'D6-12': { t: 'Can the engine handle transliteration, aliases, name order and date variations?', e: 'Test results' },
'D6-13': { t: 'Does screening scope include the customer, beneficial owner, authorised signatory, related party and counterparty?', e: 'Scope document' },
'D6-14': { t: 'Does transaction screening run in real time (pre-transaction) so that a payment can be stopped?', e: 'System architecture, sample stop' },
'D6-15': { t: 'Are the fields screened in SWIFT MT and ISO 20022 messages documented?', e: 'Field mapping document' },
'D6-16': { t: 'Are free-text fields (e.g. payment reference) screened?', e: 'Configuration record' },
'D6-17': { t: 'For trade finance transactions, are goods, vessel, port, carrier and end user screened?', e: 'Screening records, sample file' },
'D6-18': { t: 'Are dual-use goods lists and end-use declaration checks applied?', e: 'Control records' },
'D6-19': { t: 'Are vessel-related red flags (AIS gaps, ship-to-ship transfers, flag changes) monitored?', e: 'Monitoring source, detected cases' },
'D6-20': { t: 'Is the four-eyes principle applied to alert closure decisions?', e: 'Decision records' },
'D6-21': { t: 'Is the same user systemically prevented from both reviewing and approving?', e: 'System rule, breach report' },
'D6-22': { t: 'Are alert decision rationales auditable, showing who did what and when?', e: 'Sample audit trail' },
'D6-23': { t: 'Is the block/reject decision and notification process defined for a true match?', e: 'Procedure, applied cases' },
'D6-24': { t: 'Are the closure time and ageing of sanctions alerts reported?', e: 'Ageing report' },
'D6-25': { t: 'Is the screening system subject to an independent effectiveness test at least annually?', e: 'Test report (known-name set)' },
'D6-26': { t: 'Is there a manual screening and backlog remediation procedure for system outages?', e: 'Procedure, outage records' },

/* D7 — AML Transaction Monitoring */
'D7-01': { t: 'Is the scenario inventory mapped to the typology each scenario targets?', e: 'Scenario–typology matrix' },
'D7-02': { t: 'Are all typologies identified in the EWRA covered by scenarios (coverage assessment)?', e: 'Coverage analysis report' },
'D7-03': { t: 'Is there a gap log and action plan for typologies not covered?', e: 'Gap list' },
'D7-04': { t: 'Are scenario changes subject to formal change management and approval?', e: 'Change records' },
'D7-05': { t: 'Are new or amended scenarios validated in a test environment before going live?', e: 'Test reports' },
'D7-06': { t: 'Were scenario thresholds set on the basis of data analysis?', e: 'Threshold-setting study' },
'D7-07': { t: 'Have thresholds and parameters been tuned within the last 12–18 months?', e: 'Tuning report' },
'D7-08': { t: 'Is below-the-line testing performed?', e: 'BTL test report' },
'D7-09': { t: 'Is excessive alert generation assessed through above-the-line analysis?', e: 'ATL analysis report' },
'D7-10': { t: 'Is segmentation applied by customer or product group?', e: 'Segmentation document' },
'D7-11': { t: 'Is model validation performed by a team or party independent of the first and second lines?', e: 'Validation report' },
'D7-12': { t: 'Are validation findings tracked to closure?', e: 'Finding tracker' },
'D7-13': { t: 'Is the balance between alert generation volume and review capacity monitored regularly?', e: 'Capacity report' },
'D7-14': { t: 'Are the number and ageing of the open alert backlog reported?', e: 'Backlog report' },
'D7-15': { t: 'Is an SLA defined and measured for alert closure time?', e: 'SLA definition, measurement report' },
'D7-16': { t: 'Are alert closure rationales classified using a standard code set?', e: 'Code set, distribution report' },
'D7-17': { t: 'Is bulk alert closure prevented or subject to special approval?', e: 'System rule, approval records' },
'D7-18': { t: 'Are repeat alerts on the same customer consolidated and assessed holistically?', e: 'Case consolidation record' },
'D7-19': { t: 'Is network / link analysis available during investigation?', e: 'Tool usage record' },
'D7-20': { t: 'Are alert-to-case-to-STR conversion rates monitored by scenario, product and analyst?', e: 'Conversion rate report' },
'D7-21': { t: 'Are scenarios with very low productivity reviewed or retired?', e: 'Scenario performance report' },
'D7-22': { t: 'Is the quality of analyst decisions measured through regular QA sampling?', e: 'QA test report' },
'D7-23': { t: 'Does the QA error rate translate into analyst-level feedback and training?', e: 'Feedback records' },
'D7-24': { t: 'Is remediation and retrospective screening performed after monitoring system outages?', e: 'Outage and remediation record' },

/* D8 — STR, Freezing and Customer Exit */
'D8-01': { t: 'Is the suspicious transaction reporting decision process (alert – case – decision) defined in writing?', e: 'Procedure document' },
'D8-02': { t: 'Is the time from detection of suspicion to filing within the statutory limit?', e: 'Timeliness measurement report' },
'D8-03': { t: 'Are the number and causes of late filings monitored?', e: 'Delay analysis' },
'D8-04': { t: 'Are decisions not to file an STR also recorded with a rationale?', e: 'Decision records' },
'D8-05': { t: 'Does the STR narrative cover who, what, when, where, how much and why it is suspicious?', e: 'Sample narratives' },
'D8-06': { t: 'Is a standard template and QA control applied to narrative quality?', e: 'Template, QA report' },
'D8-07': { t: 'Is enhanced monitoring applied in the following period to customers subject to an STR?', e: 'Monitoring record' },
'D8-08': { t: 'Where STRs recur, is the sustainability of the customer relationship assessed?', e: 'Assessment record' },
'D8-09': { t: 'Are controls and training on the tipping-off prohibition in place?', e: 'Procedure, training record' },
'D8-10': { t: 'Is access to STR records restricted and logged?', e: 'Authorisation list, access log' },
'D8-11': { t: 'Are asset freezing decisions implemented without delay (same business day)?', e: 'Implementation timestamps' },
'D8-12': { t: 'Is the competent authority notified after a freeze?', e: 'Notification letters' },
'D8-13': { t: 'Is an inventory of frozen assets maintained and periodically reconciled?', e: 'Asset inventory' },
'D8-14': { t: 'Is the unfreezing process defined and controlled?', e: 'Procedure, implementation records' },
'D8-15': { t: 'Are exemption requests for basic expenses managed in accordance with due process?', e: 'Request and approval records' },
'D8-16': { t: 'Are the criteria for terminating a customer relationship (exit) defined in writing?', e: 'Exit policy' },
'D8-17': { t: 'Are exit decisions subject to committee or senior management approval?', e: 'Committee minutes' },
'D8-18': { t: 'Is it documented that the STR obligation was separately assessed in exit decisions?', e: 'Assessment record' },
'D8-19': { t: 'Is the financial exclusion impact of bulk de-risking assessed?', e: 'Impact analysis' },
'D8-20': { t: 'Is the return of balances and onward routing of funds controlled after exit?', e: 'Return transaction records' },
'D8-21': { t: 'Are records of declined applications maintained and checked on reapplication?', e: 'Rejection list, control rule' },
'D8-22': { t: 'Are STR, freezing and exit volumes included in regular management reporting?', e: 'Management report' },

/* D9 — Regulatory Events and Law Enforcement Requests */
'D9-01': { t: 'Is a central tracker maintained for past audit and examination findings?', e: 'Finding tracker' },
'D9-02': { t: 'Are finding closures independently re-tested?', e: 'Re-test reports' },
'D9-03': { t: 'Has the history of administrative sanctions and warnings been assessed through root cause analysis?', e: 'Root cause analysis' },
'D9-04': { t: 'Are repeat findings separately monitored and escalated?', e: 'Repeat finding report' },
'D9-05': { t: 'Is regulatory correspondence coordinated centrally and archived?', e: 'Correspondence archive' },
'D9-06': { t: 'Is there a defined owner and SLA for law enforcement and judicial information requests?', e: 'Procedure, SLA definition' },
'D9-07': { t: 'Are the completeness and timeliness of responses to requests measured?', e: 'Response time report' },
'D9-08': { t: 'Are the risk rating and monitoring of customers subject to a law enforcement request reviewed?', e: 'Review record' },
'D9-09': { t: 'Is information about a law enforcement request handled so as not to breach the tipping-off prohibition?', e: 'Access restriction, procedure' },
'D9-10': { t: 'Are requests for information (RFIs) from correspondents and counterparties managed centrally with turnaround times tracked?', e: 'RFI logging system' },
'D9-11': { t: 'Are AML questionnaires from correspondent banks answered centrally and consistently?', e: 'Completed questionnaires' },
'D9-12': { t: 'Is there a defined horizon scanning process for regulatory change?', e: 'Regulatory tracking log' },
'D9-13': { t: 'Is an impact analysis and implementation plan produced for regulatory changes?', e: 'Impact analysis documents' },
'D9-14': { t: 'Are industry typology publications (FIU, FATF, Egmont alerts) used in scenario development?', e: 'Source-to-scenario mapping record' },

/* D10 — Training, Awareness and Management Feedback */
'D10-01': { t: 'Is an annual training plan prepared and approved by the board?', e: 'Approved training plan' },
'D10-02': { t: 'Is training differentiated by role (branch, compliance, treasury, trade finance, senior management)?', e: 'Curriculum matrix' },
'D10-03': { t: 'Is mandatory induction training and its completion deadline defined for new joiners?', e: 'Induction records' },
'D10-04': { t: 'Are agent, representative and outsourced provider staff within the training scope?', e: 'Training attendance list' },
'D10-05': { t: 'Is the training completion rate tracked with full participation as the target?', e: 'Completion report' },
'D10-06': { t: 'Is escalation or consequence management applied to those who do not complete training?', e: 'Escalation records' },
'D10-07': { t: 'Are training records archived in an audit-ready manner?', e: 'Archive sample' },
'D10-08': { t: 'Is training effectiveness measured through a test or case study?', e: 'Test results' },
'D10-09': { t: 'Is training content updated with the institution\'s own typologies and real cases?', e: 'Content revision log' },
'D10-10': { t: 'Is supplementary or urgent training delivered when regulations change?', e: 'Supplementary training records' },
'D10-11': { t: 'Is the number of internal suspicion reports from staff monitored as an awareness indicator?', e: 'Internal reporting statistics' },
'D10-12': { t: 'Does the compliance officer deliver a comprehensive presentation to the board at least annually?', e: 'Board meeting minutes' },
'D10-13': { t: 'Is the management feedback loop (report – decision – action – closure) documented?', e: 'Decision and action records' },
'D10-14': { t: 'Are dedicated AML awareness sessions held for senior management and the board?', e: 'Session records' },

/* D11 — Enterprise-Wide Risk Assessment (EWRA) */
'D11-01': { t: 'Is the enterprise-wide risk assessment based on a written and approved methodology?', e: 'EWRA methodology document' },
'D11-02': { t: 'Is the EWRA updated at least annually and upon material changes?', e: 'Date of last EWRA, revision log' },
'D11-03': { t: 'Does the EWRA cover customer, product/service, geography, channel and transaction dimensions in full?', e: 'EWRA report' },
'D11-04': { t: 'Is terrorist financing risk assessed separately from money laundering risk?', e: 'TF risk section' },
'D11-05': { t: 'Is proliferation financing (PF) risk assessed?', e: 'PF risk section' },
'D11-06': { t: 'Are inherent risk and control effectiveness scored separately and residual risk calculated?', e: 'Scoring table' },
'D11-07': { t: 'Is the control effectiveness score supported by independent test findings rather than self-declaration?', e: 'Reference to test findings' },
'D11-08': { t: 'Is the data used in the assessment based on verifiable sources?', e: 'Data source list' },
'D11-09': { t: 'Are the assumptions and limitations of the EWRA stated explicitly?', e: 'Assumptions section' },
'D11-10': { t: 'Are the national risk assessment and sector reports used as inputs?', e: 'Source references' },
'D11-11': { t: 'Is risk appetite defined in writing and expressed through measurable limits?', e: 'Risk appetite statement' },
'D11-12': { t: 'Is an action plan produced for areas where residual risk exceeds appetite?', e: 'Action plan' },
'D11-13': { t: 'Do EWRA results actually influence scenarios, thresholds and KYC frequencies?', e: 'Change records (referencing the EWRA)' },
'D11-14': { t: 'Is the EWRA approved by the board?', e: 'Board approval decision' },
'D11-15': { t: 'Are branch and subsidiary risk scores consolidated?', e: 'Consolidation table' },
'D11-16': { t: 'Is the closure status of previous EWRA actions reported in the following cycle?', e: 'Closure report' }
};

/* Sample populations referenced on question rows */
const QUESTION_POPS_EN = {
  'Son 24 ayda kapatılan denetim bulguları': 'Audit findings closed in the last 24 months',
  'Son 12 ayda onaylanan yeni ürünler': 'New products approved in the last 12 months',
  'Aktif acente/dış hizmet sözleşmeleri': 'Active agent / outsourcing contracts',
  'Üçüncü taraf üzerinden açılan hesaplar': 'Accounts opened through third parties',
  'Yeni açılan tüzel kişi hesapları': 'Newly opened legal entity accounts',
  'Nakit yoğun sektör müşterileri': 'Cash-intensive sector customers',
  'PEP müşteriler': 'PEP customers',
  'Son 12 ayda açılan PEP hesapları': 'PEP accounts opened in the last 12 months',
  'Sınır ötesi işlem yapan müşteriler': 'Customers transacting cross-border',
  'Yüksek riskli ülke bağlantılı müşteriler': 'Customers linked to high-risk countries',
  'Aktif muhabir ilişkileri': 'Active correspondent relationships',
  'Son 24 ayda kurulan muhabir ilişkileri': 'Correspondent relationships established in the last 24 months',
  'Muhabir işlem akışları': 'Correspondent transaction flows',
  'Offshore yapılı müşteriler': 'Customers with offshore structures',
  'Reddedilen başvurular': 'Declined applications',
  'Son 12 ayda onaylanan ürünler': 'Products approved in the last 12 months',
  'Uzaktan açılan hesaplar': 'Remotely opened accounts',
  'Üçüncü taraf sağlayıcı işlemleri': 'Third-party provider transactions',
  'Gözetimsiz kanal işlemleri': 'Unattended channel transactions',
  'Ön ödemeli ürün işlemleri': 'Prepaid product transactions',
  'Eşik üstü nakit işlemler': 'Cash transactions above threshold',
  'VASP müşterileri': 'VASP customers',
  'Sanal varlık transferleri': 'Virtual asset transfers',
  'Unhosted cüzdan işlemleri': 'Unhosted wallet transactions',
  'Menkul kıymet işlemleri': 'Securities transactions',
  'Müşteri olmayan tek seferlik işlemler': 'Occasional transactions by non-customers',
  'Acente kanalı işlemleri': 'Agent channel transactions',
  'Günlük mutabakat kayıtları': 'Daily reconciliation records',
  'Eşik aşan mutabakat farkları': 'Reconciliation variances above threshold',
  'Son 12 aydaki besleme hataları': 'Feed failures in the last 12 months',
  'Yabancı para işlemler': 'Foreign currency transactions',
  'Müşteri-işlem eşleşme örneklemi': 'Customer-to-transaction matching sample',
  'Giden/gelen elektronik transferler': 'Outgoing and incoming wire transfers',
  'Eksik bilgili transferler': 'Transfers with missing information',
  'Son 24 aydaki değişiklikler': 'Changes in the last 24 months',
  'Yetkili kullanıcı örneklemi': 'Authorised user sample',
  'Vekil/temsilci ile açılan hesaplar': 'Accounts opened by proxy or representative',
  'Yüksek riskli yeni müşteriler': 'High-risk new customers',
  'Üst düzey yönetici uygulanan dosyalar': 'Files relying on the senior managing official',
  'Karmaşık yapılı müşteriler': 'Customers with complex structures',
  'Risk skoru override edilen müşteriler': 'Customers with overridden risk score',
  'Tetikleyici olay yaşanan müşteriler': 'Customers with a trigger event',
  'Yüksek riskli müşteriler': 'High-risk customers',
  'Gecikmiş KYC dosyaları': 'Overdue KYC files',
  'Profil sapması olan müşteriler': 'Customers deviating from profile',
  'Yeniden aktifleşen hesaplar': 'Reactivated accounts',
  'Tüm müşteri dosyaları': 'All customer files',
  'Son 12 aydaki liste güncellemeleri': 'List updates in the last 12 months',
  'Liste güncelleme olayları': 'List update events',
  'Ulusal dondurma kararları': 'National freezing decisions',
  'Yüksek riskli tüzel kişiler': 'High-risk legal entities',
  'Trade finance işlemleri': 'Trade finance transactions',
  'Bilinen isim varyasyon testleri': 'Known-name variation tests',
  'Müşteri ve karşı taraf örneklemi': 'Customer and counterparty sample',
  'Giden ödeme işlemleri': 'Outgoing payment transactions',
  'Serbest metin içeren ödemeler': 'Payments containing free text',
  'Akreditif/tahsilat dosyaları': 'Letter of credit / collection files',
  'Trade finance dosyaları': 'Trade finance files',
  'Deniz taşımacılığı dosyaları': 'Maritime shipping files',
  'True match vakaları': 'True match cases',
  'Kapatılan yaptırım alertleri': 'Closed sanctions alerts',
  'Son 12 aydaki senaryo değişiklikleri': 'Scenario changes in the last 12 months',
  'Devreye alınan senaryolar': 'Scenarios put into production',
  'Eşik altı işlem örneklemi': 'Below-threshold transaction sample',
  'Açık validasyon bulguları': 'Open validation findings',
  'Kapatılan izleme alertleri': 'Closed monitoring alerts',
  'Toplu kapatma vakaları': 'Bulk closure cases',
  'Tekrarlayan alertli müşteriler': 'Customers with repeat alerts',
  'Karmaşık vakalar': 'Complex cases',
  'Kapatılan alert ve vakalar': 'Closed alerts and cases',
  'QA hatası tespit edilen dosyalar': 'Files where a QA error was found',
  'Verilen ŞİB dosyaları': 'Filed STR files',
  'Gecikmiş ŞİB dosyaları': 'Late STR files',
  'ŞİB verilmeyen kapatılmış vakalar': 'Closed cases with no STR filed',
  'ŞİB verilen müşteriler': 'Customers subject to an STR',
  'Birden fazla ŞİB verilen müşteriler': 'Customers with multiple STRs',
  'Erişim logu örneklemi': 'Access log sample',
  'Dondurma kararları': 'Freezing decisions',
  'Dondurma vakaları': 'Freezing cases',
  'Dondurulan hesaplar': 'Frozen accounts',
  'Kaldırma vakaları': 'Unfreezing cases',
  'İstisna talepleri': 'Exemption requests',
  'Exit kararları': 'Exit decisions',
  'Exit sonrası iade işlemleri': 'Post-exit return transactions',
  'Kapatılan bulgular': 'Closed findings',
  'Alınan bilgi talepleri': 'Information requests received',
  'Yanıtlanan talepler': 'Requests answered',
  'Kolluk talebine konu müşteriler': 'Customers subject to a law enforcement request',
  'Kolluk talebi dosyaları': 'Law enforcement request files',
  "Gelen RFI'lar": 'Incoming RFIs',
  'Yanıtlanan anketler': 'Questionnaires answered',
  'Son 12 aydaki değişiklikler': 'Changes in the last 12 months',
  'Son 12 ayda işe başlayanlar': 'New joiners in the last 12 months',
  'Acente personeli': 'Agent staff',
  'Tamamlamayan personel': 'Staff who did not complete',
  'Eğitim kayıtları': 'Training records',
  'EDD dosyaları': 'EDD files',
  'Yeni açılan hesaplar': 'Newly opened accounts',
  'Tüzel kişi müşteriler': 'Legal entity customers',
  'Kesinti dönemleri': 'Outage periods'
};
